### ISSUE TITLE
add site search for newsletters

### ISSUE THREAD

**Issue by moneyball** [bitcoinops/bitcoinops.github.io#124]
The historical newsletters are really creating a treasure trove of information that increases in value each week. I did a quick google site search to demonstrate that a user can relatively easily search for content. It would be great to add site search.

https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fbitcoinops.org%2Fen%2Fnewsletters%2F+bech32&oq=site%3Ahttps%3A%2F%2Fbitcoinops.org%2Fen%2Fnewsletters%2F+bech32&aqs=chrome..69i57j69i58.3638j0j7&sourceid=chrome&ie=UTF-8

**Comment by jnewbery** [comment]
from @harding :

1. Adding a search box for Google search or another provider is easy.  I'd want it to be a static POST box so the Google doesn't get stats on our every visitor (just the ones that use the search), but that's also the easiest option.  Feel free to open an issue for that.
2. Long-term, I'd like to create some sort of topic index so that when I say "SIGHASH_NOINPUT_UNSAFE" I can just link to the page for that topic and users will get an overview plus links to our content plus links to offsite content we've curated.

I concept ACK both of those!

**Comment by bitschmidty** [comment]
Nice idea! Only comment would be that we have some content under [Blog](https://bitcoinops.org/en/blog/) as well which would be missed by the /newsletters/ in the url.

**Comment by harding** [comment]
I plan to start working on a topic index soon.  I think it should be easy, but I'm setting an ETA to end-of-June to be conservative.

**Comment by jnewbery** [comment]
Any update on this @harding ? Is there any way any of us can help to get this implemented?

**Comment by harding** [comment]
Update: I created a local branch for this and then forgot all about it.  I have a few hours to spare today, so I'll see what I can do and check back in tomorrow.

**Comment by jnewbery** [comment]
Topic index merged in #268!
