### ISSUE TITLE
House style guide

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/bitcoinops.github.io#165]
There are certain conventions that we've adopted in our newsletters over the last year. For example:

- onchain over on-chain (https://github.com/bitcoinops/bitcoinops.github.io/pull/86#discussion_r234697525)
- light client over lite client (https://github.com/bitcoinops/bitcoinops.github.io/pull/105#discussion_r251551595)
- merkle tree over Merkle tree (https://github.com/bitcoinops/bitcoinops.github.io/pull/113#discussion_r261849651)
- k-of-n multisigs over m-of-n multisigs

We should document all of these somewhere.

The Optech newsletter is very highly regarded. I expect other authors would want to follow the style conventions we use if they were documented somewhere.

**Comment by bitschmidty** [comment]
Awesome idea. Ive been adding to a similar list Ive used over the last year personally. Would this make most sense to live in github or published as an evergreen blog post on the optech website (like bech32 segment)?

**Comment by jnewbery** [comment]
paging @harding

**Comment by harding** [comment]
Concept ACK.

@bitschmidty I'd want to see how much content we have before committing to a blog post.  E.g., if it's just the four rules @jnewbery posted above, I don't think that's enough material.  Also, we might want to spend a couple months privately using the guide ourselves to ensure that it's working for us before we recommend it to other people.

Off the top of my head, here are some rules I try to follow:

- Denomination: I've been denominating everything in BTC as a compromise position between my preference for (m|u|n)BTC units and others' preference for satoshi units.

- Size: I use vbytes rather than weight units.

- Different meanings of Bitcoin: Bitcoin the system is a proper noun; bitcoin the currency is a common noun.

- Shortening Bitcoin Core: I almost never shorten "Bitcoin Core" to "Core".  Similarly, I almost never shorten "Bitcoin Core \<role\>" to "Core \<role\>".

- Unintroduced abbreviations: most abbreviations should be introduced, but I expect the following abbreviations to be well enough know by our audience that they need no introduction: BTC, LN, SI-prefixed byte sizes (e.g. kB, MB, ...), SI-prefixed binary byte sizes (e.g. kiB, MiB, ...), and probably other things I can't remember right now.

- Names: when repeating the use of a name with in the same section, I usually refer to people by their surname rather than given name (e.g. Nakamoto not Satoshi).  I never use Mr./Mrs.-type prefixes and I only use title prefixes like Dr. or Prof. unless they're especially relevant to the point being made in that section.

- Other grammar stuff: I do original compositions in my native American English but I personally think spelling should be a per-page attribute rather than a site attribute.  So if the author of a page wants to use British spelling, I think that should be their call.  When it comes to other grammar rules, I'm a dedicated adherent of The Bible AKA Strunk & White AKA [The Elements of Style](https://faculty.washington.edu/heagerty/Courses/b572/public/StrunkWhite.pdf), although I will sometimes pinch my nose, crinkle up my face, and interact with heathens who don't use the serial comma.



Some things I haven't been consistent about:

- Schnorr and Taproot as proper or common nouns.  Similar to our use of `merkle` as a common noun, I want to use these as common nouns.  However, bip-schnorr and bip-taproot use them as proper nouns and I've sometimes used that convention.

**Comment by jnewbery** [comment]
> Also, we might want to spend a couple months privately using the guide ourselves to ensure that it's working for us before we recommend it to other people.

This sounds very sensible. Shall we start with something like STYLE.md in the base directory, and if it turns out to be substantial and useful, turn it into a blog post?

> Shortening Bitcoin Core: I almost never shorten "Bitcoin Core" to "Core". Similarly, I almost never shorten "Bitcoin Core \<role\>" to "Core \<role\>".

I'd replace 'almost never' with 'never'. I can't think of any situation where using "Core" would be appropriate.

For \<role\>, I only ever use two roles when talking about the project: "Bitcoin Core contributor" and "Bitcoin Core maintainer". I avoid using constructions like "Bitcoin Core developer" because I think it can cause a misinterpretation of the relationship of the individual to the project (eg that individuals are employed by the project or that there's some kind of membership requirement to contribute code).

> Schnorr and Taproot as proper or common nouns

I don't really have a strong preference either way, as long as we're consistent. Harding writes the vast majority of the content, so I'm happy to go with his preference.

> I'm a dedicated adherent of The Bible AKA Strunk & White AKA The Elements of Style

"Write to-day, to-night, to-morrow (but not together) with hyphen." :fearful: 

Another one I've thought of:

- The abbreviation for segregated witness is segwit (uncapitalized except at the start of a sentence). It is not styled Segwit or SegWit.

**Comment by harding** [comment]
> Shall we start with something like STYLE.md in the base directory, and if it turns out to be substantial and useful, turn it into a blog post?

SGTM.  I think that also makes it something that we can quickly create using the above notes and @bitschmidty's notes, and then add to it over the next few weeks as we actually write and review stuff with it at hand.

> For <role>, I only ever use two roles when talking about the project: "Bitcoin Core contributor" and "Bitcoin Core maintainer".

I'm not so rigorous, but Bitcoin Core contributor is my go-to because it's non-specific about the type of contribution.  (Developing the software is critical, but I think reviewing is just as important.  And I like to think writing documentation helps too.  :-)  In any case, I don't mind codifying something about the role names we use.

> The abbreviation for segregated witness is segwit (uncapitalized except at the start of a sentence).

Oh, good one.  We also use ECDSA so often I had kinda forgotten that it's an abbreviation.
