### ISSUE TITLE
Transition to using Bitcoin Invoice Address

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/bitcoinops.github.io#265]
[BIP 179](https://github.com/bitcoin/bips/blob/master/bip-0179.mediawiki) suggests using _Bitcoin invoice address_ instead of _address_, to reduce confusion around whether addresses should be reused.

It was suggested here: https://github.com/bitcoinops/bitcoinops.github.io/issues/171#issuecomment-551998648 that we update the style guide to use. That suggestion was withdrawn because it seems to early for us to make this style change.

Use this issue to track whether we do want to adopt the _bitcoin invoice address_ at some point.

**Comment by jnewbery** [comment]
Related issue in Bitcoin Core: https://github.com/bitcoin/bitcoin/issues/17429

**Comment by harding** [comment]
After trying this in a newsletter draft, discussing it with some people, and thinking about it a bit, I'm currently mildly opposed to using the term "invoice address" as it's a bit unweildly to use (especially since I found I was almost always prefixing it by another word such as "bech32", "P2PKH", "P2SH", etc) and doesn't have a clear path to transitioning to a simpler term given that a Bitcoin address isn't a proper invoice since it lacks information an invoice would normally contain, such as an amount (a better example of an Bitcoin invoice would be a BIP21 URI or a BIP70 payment request).

Apologies for jumping on, and then off, this bandwagon so quickly.  I would like to reduce confusion about address reuse but I don't currently think BIP179 is the way to do it.  That said, I'm willing to use BIP179 if the rest of y'all really want it.

**Comment by jonatack** [comment]
@harding you summarised fairly well how I see it at the moment. I'm open to changing my mind but am not yet convinced that the benefits of the change at this point outweight the cost of transitioning codebases and documentation. Or not updating, and mentally accomodating the coexistance of the dual wording for the foreseeable future.

**Comment by jnewbery** [comment]
I'm also mildly opposed to us using 'Bitcoin Invoice Address' at this point in time. If the term starts getting more traction, we should reconsider whether we want to use it.

Closing for now, but happy to re-open if other people want this.
