### ISSUE TITLE
Automatic anchors generating duplicates

### ISSUE THREAD

**Issue by bitschmidty** [bitcoinops/bitcoinops.github.io#325]
In https://github.com/bitcoinops/bitcoinops.github.io/pull/313 it appears multiple`id="news"` anchor IDs are generated which now cause issue with our duplicate anchor checks.

It caused the [build of the merge of #313 to fail](https://travis-ci.org/bitcoinops/bitcoinops.github.io/builds?utm_medium=notification&utm_source=github_status)

I found this getting #324 PR opened and [got the build error ](https://travis-ci.org/bitcoinops/bitcoinops.github.io/builds/641533769?utm_source=github_status&utm_medium=notification)

**Comment by jnewbery** [comment]
This is caused by the auto-anchor plugin adding anchors to list elements with the following preference:

- if the list element has a **bold string**, use that as the id for the anchor
- else if the list element has a *italics string*, use that as the id for the anchor
- else if the list element has a [link](/dont/click/me), use that as the id for the anchor

Code is here: https://github.com/bitcoinops/bitcoinops.github.io/blob/master/_plugins/auto-anchor.rb#L14

I tried reversing that preference order so it'd prefer links over bold text, but that's not what we want. It breaks https://bitcoinops.org/en/newsletters/2019/12/18/#bitfinex-supports-ln-deposits-and-withdrawals and https://bitcoinops.org/en/newsletters/2019/12/18/#bitmex-bech32-send-support for example (and would break a bunch of old links).

I think we really want to prefer the first bold string, italics string or link in the list element for the anchor id. WDYT @harding?

**Comment by jnewbery** [comment]
I fixed it by adding a newline in the list item. Obvious really. I think that's our solution rather than messing around with the plugin.

**Comment by harding** [comment]
> I think we really want to prefer the first bold string, italics string or link in the list element for the anchor id. WDYT @harding?

Good idea and easy to do.  See #327
