### ISSUE TITLE
Automatic Anchors not populating for ja

### ISSUE THREAD

**Issue by bitschmidty** [bitcoinops/bitcoinops.github.io#348]
See the source for bullets on, for example, newsletter 72:

https://bitcoinops.org/ja/newsletters/2019/11/13/

**Comment by AkioNak** [comment]
I think this is due to the specification of autoanchor plugin (auto-anchors.rb) that is not handle non-ascii chars well. 
I recommend that inserting non-visible-bold span because it enables easy link configuration like from '-/en/-' to '-/ja/-' .

please see:
https://github.com/AkioNak/bitcoinops.github.io/blame/fixautoid/_posts/ja/newsletters/2019-11-13-newsletter-ja.md#L41

**Comment by harding** [comment]
Appears to be a problem with Kramdown, our markdown-to-html converter.  I have an easy mitigation but I need to test for side effects, so it'll be a few hours before I can open a PR.

**Comment by harding** [comment]
See #349 for a proposed solution.

**Comment by AkioNak** [comment]
Thanks. #349 is much better than my quick hack.
