### ISSUE TITLE
Need improvements to result when "make" fails

### ISSUE THREAD

**Issue by shaavan** [bitcoinops/bitcoinops.github.io#925]
Providing non-ASCII characters as the title of a section can lead to the following error, which occurs when no successful anchor link can generate.

![image](https://user-images.githubusercontent.com/85434418/200838319-a1b8e473-bc31-4f55-b37b-5e444b8fa5fc.png)

The issue is that in the presence of multiple errors of this kind, it's pretty hard to pinpoint the culprit for the error, making the debugging process unnecessarily complicated.

I tried to find a way to notify about the line number, which caused the issue, but it seems like we would need to modify the code for `html-proofer` to make this happen.

I want to discuss ways to solve this issue from our side or at least make the error less cryptic without being misleading.

**Comment by bitschmidty** [comment]
Due to this issue with the auto-anchor plugin (https://github.com/bitcoinops/bitcoinops.github.io/pull/349) we recommend that you provide a comment with ASCII. I think you are doing that for your workarounds. I dont have a better plan right now other than putting those ASCII comments in to generate usable slugs.

https://github.com/bitcoinops/bitcoinops.github.io/blob/master/CONTRIBUTING.md

> Due to https://github.com/bitcoinops/bitcoinops.github.io/pull/349 in the automatic anchoring process, some languages need HTML comments inserted into the header/bullet to ensure a unique anchor is generated. For example, see the  [comment](https://github.com/bitcoinops/bitcoinops.github.io/commit/4e450d1a1f72219ec50ad91edae605647164d25d#diff-435f99f277721eff9e2f244149575f41R41) in this Japanese newsletter.

If you have additional suggestions, let me know.

**Comment by bitschmidty** [comment]
Im going to close this issue. There is a workaround for current translations and also discussion about a bigger move for the site in terms of Jekyll upgrade or a different software for generating the site. https://github.com/bitcoinops/bitcoinops.github.io/pull/1438
